# This file is managed by 'repo_helper'. Don't edit it directly.
---

exclude: ^$

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.3.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending

 - repo: https://github.com/domdfcoding/pre-commit-hooks
   rev: v0.1.1
   hooks:
    - id: requirements-txt-sorter
      args:
       - --allow-git
    - id: check-docstring-first
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup|tests/.*)\.py$
    - id: bind-requirements

 - repo: https://github.com/domdfcoding/flake8-dunder-all
   rev: v0.1.0
   hooks:
    - id: ensure-dunder-all
      files: ^sphinx_toolbox/.*\.py$

 - repo: https://github.com/pre-commit/pygrep-hooks
   rev: v1.5.1
   hooks:
    - id: python-no-eval

 - repo: https://github.com/asottile/pyupgrade
   rev: v2.7.3
   hooks:
    - id: pyupgrade
      args:
       - --py36-plus

 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.1.9
   hooks:
    - id: remove-crlf
    - id: forbid-crlf

 - repo: https://github.com/domdfcoding/yapf-isort
   rev: v0.4.4
   hooks:
    - id: yapf-isort
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup)\.py$

 - repo: https://github.com/domdfcoding/dep_checker
   rev: v0.3.1
   hooks:
    - id: dep_checker
      args:
       - sphinx_toolbox

# Custom hooks can be added below this comment
