# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Tests

on:
  push:
    branches: ["master"]

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: "actions/checkout@v2"

      - name: Setup Python üêç
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Install dependencies üîß
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade repo_helper
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -q conda
          $CONDA/bin/conda install conda-build=3.21.0

          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda config --add channels domdfcoding

      - name: "Build and install package"
        run: |
          # This mess is only necessary because conda won't fix it themselves
          # https://github.com/conda/conda/issues/1884

          python -m repo_helper build --conda --out-dir conda-bld/noarch
          $CONDA/bin/conda index ./conda-bld || exit 1
          $CONDA/bin/conda install -c file://$(pwd)/conda-bld sphinx-toolbox -y || exit 1
