# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Linux

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.config.python-version }}"
    runs-on: "ubuntu-20.04"
    continue-on-error: ${{ matrix.config.experimental }}
    env:
      USING_COVERAGE: '3.6,3.7,3.8,3.9,3.10.0-alpha.3'

    strategy:
      fail-fast: False
      matrix:
        config:
          - {python-version: "3.6", testenvs: "py36,build", experimental: False}
          - {python-version: "3.7", testenvs: "py37,build", experimental: False}
          - {python-version: "3.8", testenvs: "py38,build", experimental: False}
          - {python-version: "3.9", testenvs: "py39,build", experimental: False}
          - {python-version: "3.10.0-alpha.3", testenvs: "py310-dev,build", experimental: True}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: "actions/checkout@v2"

      - name: Setup Python ğŸ
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.config.python-version }}"

      - name: Install dependencies ğŸ”§
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox virtualenv
          python -m pip install --upgrade coverage_pyver_pragma

      - name: "Run Tests for Python ${{ matrix.config.python-version }}"
        run: "python -m tox -e ${{ matrix.config.testenvs }}"


      - name: "Upload Coverage"
        uses: actions/upload-artifact@v2
        with:
          name: "coverage-${{ matrix.config.python-version }}"
          path: .coverage


  Coverage:
    needs: tests
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: "actions/checkout@v2"

      - name: Setup Python ğŸ
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies ğŸ”§
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coveralls coverage_pyver_pragma

      - name: "Download Coverage"
        uses: actions/download-artifact@v2
        with:
          path: coverage

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: coverage

      - name: Combine Coverage
        run: |
          shopt -s globstar
          python -m coverage combine coverage/**/.coverage

      - name: "Upload Combined Coverage Artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "combined-coverage"
          path: .coverage

      - name: "Upload Combined Coverage to Coveralls"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls

  Deploy:
    needs: tests

    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: "actions/checkout@v2"

      - name: Setup Python ğŸ
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies ğŸ”§
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox

      - name: Build distributions ğŸ“¦
        run: |
          tox -e build


      - name: Upload distribution ğŸ“¦ to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true



  Conda:
    needs: deploy
    runs-on: "ubuntu-20.04"
    if: startsWith(github.ref, 'refs/tags/') || ${{ startsWith(github.event.head_commit.message, 'Bump version') != true }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: "actions/checkout@v2"

      - name: Setup Python ğŸ
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies ğŸ”§
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade repo_helper

          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda

      - name: Build Conda ğŸ“¦
        run: |
          chmod +x .github/actions_build_conda.sh
          bash .github/actions_build_conda.sh

      - name: Deploy Conda ğŸš€
        run: |
          chmod +x .github/actions_deploy_conda.sh
          bash .github/actions_deploy_conda.sh
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
